from __future__ import annotations

# Compatibility facade: keep `paperlite.storage` import-compatible while the
# implementation lives in focused storage_* modules.
from paperlite.storage_cache import (
    CachedGroup,
    daily_cache_papers_for_rag,
    get_paper_embedding,
    paper_embedding_hash,
    paper_embedding_text,
    query_daily_cache,
    search_paper_embeddings,
    upsert_paper_embedding,
)
from paperlite.storage_crawl import (
    create_crawl_run,
    create_or_update_crawl_schedule,
    delete_crawl_schedule,
    due_crawl_schedules,
    find_reusable_crawl_run,
    finish_crawl_run,
    get_crawl_run,
    get_crawl_schedule,
    list_crawl_runs,
    list_crawl_schedules,
    mark_crawl_running,
    mark_crawl_schedule_finished,
    mark_crawl_schedule_started,
    mark_interrupted_crawl_runs_failed,
    record_source_result,
    runtime_storage_summary,
    store_daily_papers,
    update_crawl_schedule_status,
    upsert_paper,
)
from paperlite.storage_library import (
    apply_library_action,
    get_library_state,
    library_key_for_paper,
    list_library_events,
    list_library_items,
)
from paperlite.storage_preferences import (
    clear_preference_learning_data,
    delete_preference_prompt,
    evaluate_preference_learning,
    export_preference_training_data,
    get_preference_profile,
    get_preference_settings,
    get_relevant_preference_profile,
    list_preference_prompts,
    list_preference_queries,
    purify_preference_signals,
    rebuild_preference_profile,
    record_preference_query,
    save_preference_prompt,
    update_preference_prompt,
    update_preference_settings,
)
from paperlite.storage_schema import (
    EXPECTED_SCHEMA_COLUMNS,
    SCHEMA_VERSION,
    connect,
    default_db_path,
    init_db,
    split_source_keys,
)
from paperlite.storage_translation import get_translation_cache, upsert_translation_cache
from paperlite.storage_views import delete_saved_view, list_saved_views, save_view

__all__ = [
    "CachedGroup",
    "EXPECTED_SCHEMA_COLUMNS",
    "SCHEMA_VERSION",
    "apply_library_action",
    "clear_preference_learning_data",
    "connect",
    "create_crawl_run",
    "create_or_update_crawl_schedule",
    "daily_cache_papers_for_rag",
    "default_db_path",
    "delete_crawl_schedule",
    "delete_preference_prompt",
    "delete_saved_view",
    "due_crawl_schedules",
    "evaluate_preference_learning",
    "export_preference_training_data",
    "find_reusable_crawl_run",
    "finish_crawl_run",
    "get_crawl_run",
    "get_crawl_schedule",
    "get_library_state",
    "get_paper_embedding",
    "get_preference_profile",
    "get_preference_settings",
    "get_relevant_preference_profile",
    "get_translation_cache",
    "init_db",
    "library_key_for_paper",
    "list_crawl_runs",
    "list_crawl_schedules",
    "list_library_events",
    "list_library_items",
    "list_preference_prompts",
    "list_preference_queries",
    "list_saved_views",
    "mark_crawl_running",
    "mark_crawl_schedule_finished",
    "mark_crawl_schedule_started",
    "mark_interrupted_crawl_runs_failed",
    "paper_embedding_hash",
    "paper_embedding_text",
    "purify_preference_signals",
    "query_daily_cache",
    "rebuild_preference_profile",
    "record_preference_query",
    "record_source_result",
    "runtime_storage_summary",
    "save_preference_prompt",
    "save_view",
    "search_paper_embeddings",
    "split_source_keys",
    "store_daily_papers",
    "update_crawl_schedule_status",
    "update_preference_prompt",
    "update_preference_settings",
    "upsert_paper",
    "upsert_paper_embedding",
    "upsert_translation_cache",
]
